apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: marathon-app-service-monitor
  labels:
    app: prometheus
    release: prometheus
  namespace: default
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: marathon-service-api
  endpoints:
    - port: http-metrics
      interval: 15s
